### ISSUE TITLE
Follow @wearerequired/eslint-config

### ISSUE THREAD

**Issue by szepeviktor** [wearerequired/slack-messaging-action#3]
👉 

```
npm install prettier --save-dev
node_modules/.bin/eslint --fix index.js
```

Done 🍏

**Comment by ocean90** [comment]
The config is already used: https://github.com/wearerequired/slack-messaging-action/blob/004082e701ab3435f175750555b611869566bc57/.eslintrc.js#L1-L3

**Comment by szepeviktor** [comment]
@ocean90 The code (index.js) does not follow it.
That is why I've opened this issue.

**Comment by ocean90** [comment]
It does, as you can see in #4.

**Comment by szepeviktor** [comment]
Thank you.
Why do the above command give me a lot of differences?
